import { useCallback, useEffect, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { adminApi } from "../api";
import { Button, Card, Chip, Empty, ErrorNotice, Field, FormModal, Page, ui } from "../components/ui";
import type { Expense } from "../types";
import { errorMessage, money, taipeiDate } from "../utils";

const categories = ["設備", "設備費用", "日常消耗", "電費", "水費", "瓦斯費", "食材", "租金", "其他"];
const fresh = (): Partial<Expense> => ({ expenseDate: taipeiDate(), category: "日常消耗", name: "", amount: 0, note: "" });
export function ExpensesScreen() {
  const [items, setItems] = useState<Expense[]>([]); const [form, setForm] = useState<Partial<Expense>>(fresh()); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [category, setCategory] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems(await adminApi.listExpenses({ startDate: startDate || undefined, endDate: endDate || undefined, category: category || undefined, pageSize: 100 })); } catch (reason) { setError(errorMessage(reason, "讀取成本失敗")); } finally { setLoading(false); } }, [startDate, endDate, category]);
  useEffect(() => { void load(); }, []); // Initial load only; filters are applied explicitly.
  const edit = (item?: Expense) => { setForm(item ? { ...item, expenseDate: item.expenseDate.slice(0, 10) } : fresh()); setError(""); setOpen(true); };
  const save = async () => { if (!form.name?.trim() || !form.expenseDate || Number(form.amount) <= 0) { setError("請確認日期、名稱與金額"); return; } setLoading(true); try { await adminApi.saveExpense({ ...form, name: form.name.trim(), amount: Number(form.amount), category: form.category || "日常消耗" }); setOpen(false); await load(); } catch (reason) { setError(errorMessage(reason, "儲存成本失敗")); setLoading(false); } };
  const remove = (item: Expense) => Alert.alert("刪除成本", `確定刪除「${item.name}」？`, [{ text: "返回", style: "cancel" }, { text: "刪除", style: "destructive", onPress: async () => { try { await adminApi.deleteExpense(item.id); await load(); } catch (reason) { setError(errorMessage(reason, "刪除成本失敗")); } } }]);
  const reset = () => { setStartDate(""); setEndDate(""); setCategory(""); setTimeout(() => void adminApi.listExpenses({ pageSize: 100 }).then(setItems).catch((reason) => setError(errorMessage(reason, "讀取成本失敗"))), 0); };
  return <Page title="成本" subtitle="記錄門市支出並依日期或分類篩選" refreshing={loading} onRefresh={() => void load()} action={<Button label="新增成本" onPress={() => edit()} />}>
    <Card><Text style={ui.sectionTitle}>查詢條件</Text><View style={ui.row}><Field label="起始日期" placeholder="YYYY-MM-DD" value={startDate} onChangeText={setStartDate} /><Field label="結束日期" placeholder="YYYY-MM-DD" value={endDate} onChangeText={setEndDate} /></View><Text style={ui.muted}>分類</Text><View style={ui.row}><Chip label="全部" selected={!category} onPress={() => setCategory("")} />{categories.map((value) => <Chip key={value} label={value} selected={category === value} onPress={() => setCategory(value)} />)}</View><View style={ui.actions}><Button label="清除" variant="secondary" onPress={reset} /><Button label="查詢" loading={loading} onPress={() => void load()} /></View></Card>
    <ErrorNotice message={error} />{items.length ? <View style={ui.gap}>{items.map((item) => <Card key={item.id}><View style={ui.spread}><View style={styles.info}><View style={ui.row}><Text style={ui.strong}>{item.name}</Text><Chip label={item.category} /></View><Text style={ui.muted}>{item.expenseDate.slice(0, 10)}{item.note ? ` · ${item.note}` : ""}</Text></View><Text style={styles.amount}>{money(item.amount)}</Text><View style={ui.actions}><Button label="編輯" variant="secondary" small onPress={() => edit(item)} /><Button label="刪除" variant="danger" small onPress={() => remove(item)} /></View></View></Card>)}</View> : <Empty text="查無成本資料" />}
    <FormModal visible={open} title={form.id ? "編輯成本" : "新增成本"} onClose={() => setOpen(false)}><View style={ui.row}><Field label="日期" placeholder="YYYY-MM-DD" value={form.expenseDate || ""} onChangeText={(expenseDate) => setForm({ ...form, expenseDate })} /><Field label="名稱" value={form.name || ""} onChangeText={(name) => setForm({ ...form, name })} /><Field label="金額" keyboardType="number-pad" value={String(form.amount ?? 0)} onChangeText={(value) => setForm({ ...form, amount: Number(value) || 0 })} /></View><Text style={ui.title}>分類</Text><View style={ui.row}>{categories.map((value) => <Chip key={value} label={value} selected={form.category === value} onPress={() => setForm({ ...form, category: value })} />)}</View><Field label="備註" multiline value={form.note || ""} onChangeText={(note) => setForm({ ...form, note })} /><ErrorNotice message={error} /><View style={ui.actions}><Button label="取消" variant="secondary" onPress={() => setOpen(false)} /><Button label="儲存" loading={loading} onPress={() => void save()} /></View></FormModal>
  </Page>;
}
const styles = StyleSheet.create({ info: { minWidth: 260, flex: 1, gap: 7 }, amount: { fontSize: 18, fontWeight: "800" } });
