import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { adminApi } from "../api";
import { Button, Card, Chip, Empty, ErrorNotice, Field, FormModal, Page, ToggleField, ui } from "../components/ui";
import type { Flavor, Product } from "../types";
import { errorMessage, money } from "../utils";

type Form = Partial<Product> & { flavorIds: string[] };
const fresh = (flavors: Flavor[]): Form => ({ name: "", description: "", price: 0, cost: 0, sortOrder: 0, isActive: true, flavorIds: flavors.filter((item) => item.isActive).map((item) => item.id) });
export function ProductsScreen() {
  const [items, setItems] = useState<Product[]>([]); const [flavors, setFlavors] = useState<Flavor[]>([]); const [form, setForm] = useState<Form>(fresh([])); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const activeFlavors = useMemo(() => flavors.filter((item) => item.isActive), [flavors]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [products, flavorItems] = await Promise.all([adminApi.listProducts(), adminApi.listFlavors()]); setItems(products); setFlavors(flavorItems); } catch (reason) { setError(errorMessage(reason, "讀取商品失敗")); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const edit = (item?: Product) => { setForm(item ? { ...item, flavorIds: item.productFlavors?.map((value) => value.flavorId) || [] } : fresh(flavors)); setError(""); setOpen(true); };
  const toggleFlavor = (id: string) => setForm({ ...form, flavorIds: form.flavorIds.includes(id) ? form.flavorIds.filter((value) => value !== id) : [...form.flavorIds, id] });
  const save = async () => { if (!form.name?.trim() || Number(form.price) < 0 || Number(form.cost) < 0) { setError("請確認商品名稱、售價與成本"); return; } setLoading(true); try { await adminApi.saveProduct({ ...form, name: form.name.trim() }); setOpen(false); await load(); } catch (reason) { setError(errorMessage(reason, "儲存商品失敗")); setLoading(false); } };
  const remove = (item: Product) => Alert.alert("刪除商品", `確定刪除「${item.name}」？歷史訂單仍會保留商品快照。`, [{ text: "返回", style: "cancel" }, { text: "刪除", style: "destructive", onPress: async () => { try { await adminApi.deleteProduct(item.id); await load(); } catch (reason) { setError(errorMessage(reason, "刪除商品失敗")); } } }]);
  const names = (item: Product) => item.productFlavors?.map((value) => value.flavor.name).join("、") || "尚未設定";
  return <Page title="商品" subtitle="維護商品內容、價格、成本與可選口味" refreshing={loading} onRefresh={() => void load()} action={<Button label="新增商品" onPress={() => edit()} />}><ErrorNotice message={error} />{items.length ? <View style={styles.grid}>{items.map((item) => <Card key={item.id} style={styles.item}><View style={ui.spread}><View style={styles.info}><View style={ui.row}><Text style={ui.strong}>{item.name}</Text><Chip label={item.isActive ? "啟用" : "停用"} tone={item.isActive ? "success" : "default"} /></View><Text style={styles.price}>{money(item.price)}</Text><Text style={ui.muted}>商品成本：{money(item.cost)}</Text><Text style={ui.muted}>{item.description || "沒有商品說明"}</Text><Text style={ui.muted}>口味：{names(item)} · 排序 {item.sortOrder}</Text></View><View style={ui.actions}><Button label="編輯" variant="secondary" small onPress={() => edit(item)} /><Button label="刪除" variant="danger" small onPress={() => remove(item)} /></View></View></Card>)}</View> : <Empty text="目前沒有商品" />}
    <FormModal visible={open} title={form.id ? "編輯商品" : "新增商品"} subtitle="商品名稱、售價與口味都會顯示在點餐介面，成本只用於報表" onClose={() => setOpen(false)}><View style={ui.row}><Field label="商品名稱" value={form.name || ""} onChangeText={(name) => setForm({ ...form, name })} /><Field label="售價" keyboardType="number-pad" value={String(form.price ?? 0)} onChangeText={(value) => setForm({ ...form, price: Number(value) || 0 })} /><Field label="商品成本" keyboardType="number-pad" value={String(form.cost ?? 0)} onChangeText={(value) => setForm({ ...form, cost: Number(value) || 0 })} /><Field label="排序" keyboardType="number-pad" value={String(form.sortOrder ?? 0)} onChangeText={(value) => setForm({ ...form, sortOrder: Number(value) || 0 })} /></View><Field label="商品說明" multiline value={form.description || ""} onChangeText={(description) => setForm({ ...form, description })} /><ToggleField label="啟用" value={form.isActive ?? true} onValueChange={(isActive) => setForm({ ...form, isActive })} /><View style={ui.gap}><Text style={ui.title}>可選口味</Text><View style={ui.row}>{activeFlavors.map((flavor) => <Chip key={flavor.id} label={`${flavor.name}${flavor.extraPrice ? ` +${flavor.extraPrice}` : ""}`} selected={form.flavorIds.includes(flavor.id)} onPress={() => toggleFlavor(flavor.id)} />)}{!activeFlavors.length ? <Text style={ui.muted}>目前沒有啟用口味</Text> : null}</View></View><ErrorNotice message={error} /><View style={ui.actions}><Button label="取消" variant="secondary" onPress={() => setOpen(false)} /><Button label="儲存" loading={loading} onPress={() => void save()} /></View></FormModal>
  </Page>;
}
const styles = StyleSheet.create({ grid: { gap: 12 }, item: { width: "100%" }, info: { flex: 1, minWidth: 260, gap: 7 }, price: { fontSize: 20, fontWeight: "800" } });
